* --- Jour 8: Collinarité résonnante ---

Vous vous retrouvez sur le toit d'une installation de lapin de Pâques haut àcresses.

Alors que les Historiens font leur truc, vous regardez l'énorme antenne familière. À votre grande surprise, il semble avoir été reconfiguré pour émettre un signal qui rend les gens 0,1 % plus susceptibles d'acheter Easter Bunny marque Imitation Mediocre Chocolate en cadeau de Noel. Impoissant.

En scannant à travers la ville, vous trouvez qu'il y a en fait beaucoup de ces antennes. Chaque antenne est réglée sur une fréquence spécifique indiquée par une seule lettre minuscule, une lettre majuscule ou un chiffre. Vous créez une carte (votre jeu d'interventions de puzzle) de ces antennes. Par exemple:

............
........0...
.....0......
.......0....
....0.......
......A.....
............
............
........A...
.........A..
............
............

Le signal n'applique que son effet néfaste à des anti-noeuds spécifiques en fonction des fréquences de résonance des antennes. En particulier, un anti-noeud se produit en tout point qui est parfaitement conforme à deux antennes de la même fréquence - mais seulement lorsque l'une des antennes est deux fois plus loin que l'autre. Cela signifie que pour toute paire d'antennes de même fréquence, il y a deux anti-noeuds, un de part et d'autre d'entre eux.

Donc, pour ces deux antennes avec fréquence a, ils créent les deux antinodes marqués avec #:

..........
...#......
..........
....a.....
..........
.....a....
..........
......#...
..........
..........

L'ajout d'une troisième antenne de même fréquence crée plusieurs anti-noeuds supplémentaires. Il ajouterait idéalement quatre anti-noeuds, mais deux sont du côté droit de la carte, donc à la place il n'en ajoute que deux:

..........
...#......
#.........
....a.....
........a.
.....a....
..#.......
......#...
..........
..........

Les antennes avec des fréquences différentes ne créent pas d'antinodes; A et a compter comme fréquences différentes. Cependant, les anti-noeuds peuvent se produisent à des endroits qui contiennent des antennes. Dans ce diagramme, l'antenne solitaire à capital de fréquence A ne crée pas d'antinodes mais a un minusculea- l'antinode de fréquence à son emplacement:

..........
...#......
#.........
....a.....
........a.
.....a....
..#.......
......A...
..........
..........

Le premier exemple a des antennes avec deux fréquences différentes, donc les anti-noeuds qu'ils créent ressemblent à ça, plus un antinoeud chevauchant le top le plus haut A- antenne de fréquence:

......#....#
...#....0...
....#0....#.
..#....0....
....0....#..
.#....A.....
...#........
#......#....
........A...
.........A..
..........#.
..........#.

Parce que le plus haut A- l'antenne de fréquence se chevauche avec a 0- l'antinode de fréquence, il y a 14 des emplacements uniques qui contiennent un antinoeud dans les limites de la carte.

Calculer l'impact du signal. Combien d'emplacements uniques dans les limites de la carte contiennent un antinoeud ?

Votre réponse de puzzle a été *240*.

--- Deuxième partie ---

Surveillant votre épaule pendant que vous travaillez, l'un des Historiens demande si vous avez pris les effets des harmoniques résonantes dans vos calculs.

C'est à toi.

Après la mise à jour de votre modèle, il s'avère qu'un antipne se produit à n'importe quelle position de grille exactement alignée avec au moins deux antennes de la même fréquence, quelle que soit la distance. Cela signifie que certains des nouveaux antinoes se produiront à l'endroit de chaque antenne (à moins que l'antenne soit la seule de sa fréquence).

Donc, ces trois T- les antennes de fréquence créent maintenant de nombreux antinoeuds:

T....#....
...T......
.T....#...
.........#
..#.......
..........
...#......
..........
....#.....
..........

En fait, les trois T- les antennes de fréquence sont toutes exactement conformes à deux antennes, donc elles sont toutes également anti-noeuds. Ceci apporte le nombre total d'antinodes dans l'exemple ci-dessus à 9.

L'exemple original a maintenant 34 antinoeuds, y compris les antinodes qui apparaissent sur chaque antenne:

##....#....#
.#.#....0...
..#.#0....#.
..##...0....
....0....#..
.#...#A....#
...#..#.....
#....#.#....
..#.....A...
....#....A..
.#........#.
...#......##

Calculer l'impact du signal à l'aide de ce modèle mis à jour. Combien d'emplacements uniques dans les limites de la carte contiennent un antinoeud ?

Votre réponse de puzzle a été *955*.

Les deux parties de ce puzzle sont terminées. Ils fournissent deux étoiles d'or:

À ce stade, vous devriez revenir à votre calendrier de l'Avent et essayer un autre puzzle.

Si vous voulez toujours le voir, vous pouvez obtenir votre entrée de puzzle.
