* --- Jour 5 : File d'information ---

Satisfaite de leur recherche sur Ceres, l'escadron de savants suggère par la suite de balayer les piles de papeterie du sous-sous-sous-base 17.

Le département d'impression du pôle Nord est plus fréquent que jamais, à proximité des fêtes de fin d'année, et tandis que les Historiens continuent leur recherche dans cette installation historiquement importante, un Elfe qui exploite une imprimante très familière vous prévaudait.

L'Elf doit vous reconnaître, parce qu'ils ne perdent pas de temps à expliquer que les nouvelles mises à jour du manuel de sécurité du lancement du chariot ne seront pas imprimées correctement. Ne pas mettre à jour les manuels de sécurité serait terrible en effet, vous offrez donc vos services.

Les protocoles de sécurité indiquent clairement que les nouvelles pages pour les manuels de sécurité doivent être imprimées dans un ordre très spécifique. La notation X|Y signifie que si les deux numéros de page X et numéro de page Y doivent être produites dans le cadre d'une mise à jour, numéro de page X doit être imprimé à un moment donné avant le numéro de page Y.

L'Elf a pour vous à la fois les règles d'ordre de page et les pages à produire dans chaque mise à jour (votre saisie de puzzle), mais ne peut pas déterminer si chaque mise à jour a les pages dans le bon ordre.

Par exemple:

47|53
97|13
97|61
97|47
75|29
61|13
75|53
29|13
97|29
53|29
61|53
97|53
61|29
47|13
75|47
97|75
47|61
75|61
47|29
75|13
53|13

75,47,61,53,29
97,61,53,29,13
75,29,13
75,97,47,61,53
61,13,29
97,13,75,29,47

La première section précise la Règles de commande de page, un par ligne. La première règle, 47|53, signifie que si une mise à jour inclut à la fois la page numéro 47 et la page numéro 53, alors le numéro de page 47 doit être imprimés à un moment ou à un autre avant le numéro de page 53. (47 n'a pas nécessairement besoin d'être immédiatement avant 53; les autres pages sont autorisées à être entre elles.)

La deuxième section précise les numéros de page de chaque mise à jour. Étant donné que la plupart des manuels de sécurité sont différents, les pages nécessaires dans les mises à jour sont également différentes. La première mise à jour, 75,47,61,53,29, signifie que la mise à jour se compose des pages des numéros 75, 47, 61, 53 et 29.

Pour faire démarrer les imprimantes dès que possible, commencez par identifier les mises à jour qui sont déjà dans le bon ordre.

Dans l'exemple ci-dessus, la première mise à jour (75,47,61,53,29) est dans le bon ordre:

    75 est d'abord correct parce qu'il y a des règles qui se mettent une page après l'autre: 75|47, 75|61, 75|53, et 75|29.
    47 est à peine seconde parce que 75 doit être avant elle (75|47) et toutes les autres pages doivent être après elle conformément à 47|61, 47|53, et 47|29.
    61 est correctement au milieu car 75 et 47 sont avant lui (75|61 et 47|61) et 53 et 29 sont après elle (61|53 et 61|29).
    53 est à juste titre de la quatrième parce qu'il est avant la page numéro 29 (53|29).
    29 est la seule page restante et donc est donc en fin de compte.

Étant donné que la première mise à jour n'inclut pas certains numéros de page, les règles d'ordre impliquant les numéros de page manquants sont ignorées.

Les deuxième et troisième mises à jour sont également dans le bon ordre selon les règles. Comme la première mise à jour, elles n'incluent pas non plus tous les numéros de page, et donc seules certaines des règles de commande s'appliquent - dans chaque mise à jour, les règles d'ordonnancement qui impliquent des numéros de page manquants ne sont pas utilisées.

La quatrième mise à jour, 75,97,47,61,53, est-il non dans l'ordre correct: il imprimerait 75 avant 97, ce qui viole la règle 97|75.

La cinquième mise à jour, 61,13,29, est-il aussi non dans le bon ordre, puisqu'il enfreint la règle 29|13.

La dernière mise à jour, 97,13,75,29,47, est-il non dans l'ordre correct dû à l'enfreindre plusieurs règles.

Pour une raison quelconque, les Elfes ont également besoin de connaître le numéro de page intermédiaire de chaque mise à jour en cours d'impression. Étant donné que vous n'imprimez actuellement que les mises à jour correctement ordonnées, vous aurez besoin de trouver le numéro de page du milieu de chaque mise à jour correctement ordonnée. Dans l'exemple ci-dessus, les mises à jour correctement ordonnées sont:

75,47,61,53,29
97,61,53,29,13
75,29,13

Ceux-ci ont des numéros de page du milieu de 61, 53, et 29 respectivement. L'ajout de ces numéros de page ensemble donne 143.

Bien sûr, vous aurez besoin d'être prudent: la liste réelle des règles de commande de page est plus grande et plus compliquée que l'exemple ci-dessus.

Déterminer quelles mises à jour sont déjà dans l'ordre correct. Qu'obtenez-vous si vous additionnez le numéro de page du milieu à partir de ces mises à jour correctement ordonnées ?

Votre réponse de puzzle a été *5248*.
--- Deuxième partie ---

Alors que les Elfes travaillent à imprimer les mises à jour correctement ordonnées, vous avez un peu de temps pour réparer le reste d'entre eux.

Pour chacune des mises à jour mal ordonnées, utilisez les règles de commande de page pour mettre les numéros de page dans le bon ordre. Pour l'exemple ci-dessus, voici les trois mises à jour mal ordonnées et leurs commandes correctes:

    75,97,47,61,53 devient 97,75,47,61,53.
    61,13,29 devient 61,29,13.
    97,13,75,29,47 devient 97,75,47,29,13.

Après prise Seules les mises à jour mal ordonnées et en les ordonnant correctement, leurs numéros de page du milieu sont 47, 29, et 47. En les additionnant ensemble, il produit 123.

Trouvez les mises à jour qui ne sont pas dans le bon ordre. Qu'obtenez-vous si vous additionnez les numéros de page du milieu après avoir correctement commandé ces mises à jour ?

Votre réponse de puzzle a été *4507*.

Les deux parties de ce puzzle sont terminées. Ils fournissent deux étoiles d'or:

À ce stade, vous devriez revenir à votre calendrier de l'Avent et essayer un autre puzzle.

Si vous voulez toujours le voir, vous pouvez obtenir votre entrée de puzzle.

Vous pouvez aussi 
