
* --- Jour 12 : Groupes de jardin ---

Pourquoi ne pas chercher l'historien en chef près du jardinier et de sa vaste ferme ? Il y a beaucoup de nourriture, alors les Historiens attrapent quelque chose à manger pendant qu'ils fouillent.

Vous êtes sur le point de vous installer à proximité d'un arrangement complexe de parcelles de jardin quand certains Elfes vous demandent si vous pouvez prêter main forte. Ils aimeraient mettre en place des clôtures autour de chaque région de parcelles de jardin, mais ils ne peuvent pas comprendre combien de clôtures ils doivent commander ou combien cela coûtera. Ils vous donnent une carte (votre jeu d'intrigues) des parcelles de jardin.

Chaque parcelle de jardin ne cultive qu'un seul type de plante et est indiquée par une seule lettre sur votre carte. Lorsque plusieurs parcelles de jardin cultivent le même type de plante et se touchent (horizontalement ou verticalement), elles forment une région. Par exemple:

AAAA
BBCD
BBCC
EEEC

Cet arrangement 4x4 comprend des parcelles de jardin cultivant cinq types de plantes différentes (marquées A, B, C, D, et E), chacun groupé dans sa propre région.

Afin de calculer avec précision le coût de la clôture autour d'une même région, il faut connaître la zone et le périmètre de cette région.

Le zone d'une région est simplement le nombre de parcelles de jardin que contient la région. Type de carte ci-dessus A, B, et C les plantes sont chacune dans une région de superficie 4. Le type E les plantes se trouvent dans une région 3; le type D les plantes se trouvent dans une région 1.

Chaque parcelle de jardin est une place et il en a donc quatre côtés. Le périmètre d'une région est le nombre de côtés de parcelles de jardin dans la région qui ne touchent pas un autre jardin dans la même région. Le type A et C les plantes sont chacune dans une région à périmètre 10. Le type B et E les plantes sont chacune dans une région à périmètre 8. Le sol D une parcelle forme sa propre région avec un périmètre 4.

Visuellement indiquant les côtés des placettes dans chaque région qui contribuent au pourtour en utilisant - et |, les périmètres des régions de la carte ci-dessus sont mesurés comme suit:

+-+-+-+-+
|A A A A|
+-+-+-+-+     +-+
              |D|
+-+-+   +-+   +-+
|B B|   |C|
+   +   + +-+
|B B|   |C C|
+-+-+   +-+ +
          |C|
+-+-+-+   +-+
|E E E|
+-+-+-+

Des plantes du même type peuvent apparaître dans plusieurs régions distinctes, et des régions peuvent même apparaître dans d'autres régions. Par exemple:

OOOOO
OXOXO
OOOOO
OXOXO
OOOOO

La carte ci-dessus contient 5 les régions, dont la totalité O les parcelles de jardin, et les quatre autres contenant chacune une seule X parcelle.

Les quatre X les régions ont chacune une superficie 1 et le périmètre 4. La région contenant 21 type O les plantes sont plus compliquées; en plus de son bord extérieur contribuant à un périmètre de 20, sa frontière avec chaque X la région apporte une contribution supplémentaire 4 à son périmètre, pour un périmètre total de 36.

En raison des pratiques commerciales "modernes", le prix de la clôture requise pour une région est trouvé en multipliant la zone de cette région par son périmètre. Le prix total de la clôture de toutes les régions sur une carte est trouvé en additionnant le prix de la clôture pour chaque région sur la carte.

Dans le premier exemple, région A a un prix 4 * 10 = 40, région B a un prix 4 * 8 = 32, région C a un prix 4 * 10 = 40, région D a un prix 1 * 4 = 4, et la région E a un prix 3 * 8 = 24. Donc, le prix total pour le premier exemple est 140.

Dans le deuxième cas, la région avec la totalité de la O les végétaux ont un prix 21 * 36 = 756, et chacun des quatre plus petits X les régions ont un prix 1 * 4 = 4, pour un prix total de 772 (756 + 4 + 4 + 4 + 4).

Voici un plus grand exemple :

RRRRIICCFF
RRRRIICCCF
VVRRRCCFFF
VVRCCCJFFF
VVVVCJJCFE
VVIVCCJJEE
VVIIICJJEE
MIIIIIJJEE
MIIISIJEEE
MMMISSJEEE

Il contient :

    Une région de R plantes à prix 12 * 18 = 216.
    Une région de I plantes à prix 4 * 8 = 32.
    Une région de C plantes à prix 14 * 28 = 392.
    Une région de F plantes à prix 10 * 18 = 180.
    Une région de V plantes à prix 13 * 20 = 260.
    Une région de J plantes à prix 11 * 20 = 220.
    Une région de C plantes à prix 1 * 4 = 4.
    Une région de E plantes à prix 13 * 18 = 234.
    Une région de I plantes à prix 14 * 22 = 308.
    Une région de M plantes à prix 5 * 12 = 60.
    Une région de S plantes à prix 3 * 8 = 24.

Donc, il a un prix total de 1930.

Quel est le prix total de la clôture dans toutes les régions de votre carte?

Votre réponse de puzzle a été *1549354*.

--- Deuxième partie ---

Heureusement, les Elfes essaient de commander tellement de clôtures qu'ils ont droit à une remise en gros.

Sous la réduction de gros, au lieu d'utiliser le périmètre pour calculer le prix, vous devez utiliser le nombre de côtés que chaque région a. Chaque section droite de clôture compte comme un côté, quelle que soit sa durée.

Réexaminer cet exemple à nouveau:

AAAA
BBCD
BBCC
EEEC

La région contenant le type A les plantes ont 4 côtés, de même que chacune des régions contenant des plantes de type B, D, et E. Toutefois, la région plus complexe contenant les plantes de type C a 8 les parties:

En utilisant la nouvelle méthode de calcul du prix par région en multipliant la zone de la région par son nombre de côtés, A par E avoir des prix 16, 16, 32, 4, et 12, respectivement, pour un prix total de 80.

Le deuxième example ci-dessus (plein de type X et O ) aurait un prix total de 436.

Voici une carte qui comprend une région en forme de E pleine de type E plantes:

EEEEE
EXXXX
EEEEE
EXXXX
EEEEE

La région en forme de E a une superficie de 17 et 12 pour un prix de 204. Y compris les deux régions pleines de type X plantes, cette carte a un prix total de 236.

Cette carte a un prix total de 368:

AAAAAA
AAABBA
AAABBA
ABBAAA
ABBAAA
AAAAAA

Il comprend deux régions pleines de type B plantes (chacun avec 4 côtés) et une seule région pleine de type A plantes (avec 4 de côté à l'extérieur et 8 plus de côtés à l'intérieur, un total de 12 les côtés). Soyez particulièrement prudent lorsque vous comptez la clôture autour de régions comme celle pleine de type A plantes; en particulier, chaque section de clôture a un côté et une face à l'extérieur, de sorte que la clôture ne se connecte pas à travers le milieu de la région (où les deux B les régions se touchent en diagonale). (Les Elfes auraient utilisé la société d'escrime M'bius à la place, mais leurs clauses contractuelles étaient trop partiales.)

Le plus grand exemple d'avant-prix est la mise à jour suivante:

    Une région de R plantes à prix 12 * 10 = 120.
    Une région de I plantes à prix 4 * 4 = 16.
    Une région de C plantes à prix 14 * 22 = 308.
    Une région de F plantes à prix 10 * 12 = 120.
    Une région de V plantes à prix 13 * 10 = 130.
    Une région de J plantes à prix 11 * 12 = 132.
    Une région de C plantes à prix 1 * 4 = 4.
    Une région de E plantes à prix 13 * 8 = 104.
    Une région de I plantes à prix 14 * 16 = 224.
    Une région de M plantes à prix 5 * 6 = 30.
    Une région de S plantes à prix 3 * 6 = 18.

En les additionnant ensemble, il produit son nouveau prix total de 1206.

Quel est le nouveau prix total de la clôture de toutes les régions sur votre carte?

Votre réponse de puzzle a été *937032*.

Les deux parties de ce puzzle sont terminées. Ils fournissent deux étoiles d'or:
