* --- Jour 13 : Contraption des griffes ---

Ensuite, le hall d'un complexe sur une île tropicale. Les Historiens prennent un moment pour admirer les carreaux hexagonaux avant de s'étendre.

Heureusement, on dirait que la station balnéaire a un nouvel arcade. Peut-être pouvez-vous gagner des prix des machines à griffer ?

Les machines à griffes ici sont un peu inhabituelles. Au lieu d'un joystick ou de boutons directionnels pour contrôler la griffe, ces machines ont deux boutons étiquetés A et B. Pire, vous ne pouvez pas simplement mettre un jeton et jouer; ça coûte 3 jetons pour pousser le A bouton et bouton et 1 jeton pour pousser le B bouton.

Avec un peu d'expérimentation, vous comprenez que les boutons de chaque machine sont configurés pour déplacer la griffe d'un montant spécifique à la droit (le long de la X axe) et un montant spécifique à l'avance (le long de la Y axe) chaque fois que l'on appuie sur le bouton.

Chaque machine en contient une Prix; pour remporter le prix, la griffe doit être positionnée Exactement exactement ci-dessus du prix à la fois X et Y axes.

Vous vous demandez : quel est le plus petit nombre de jetons que vous auriez à dépenser pour gagner autant de prix que possible ? Vous assemblez une liste du comportement du bouton de chaque machine et de l'emplacement du prix (votre entrée de puzzle). Par exemple:

Button A: X+94, Y+34
Button B: X+22, Y+67
Prize: X=8400, Y=5400

Button A: X+26, Y+66
Button B: X+67, Y+21
Prize: X=12748, Y=12176

Button A: X+17, Y+86
Button B: X+84, Y+37
Prize: X=7870, Y=6450

Button A: X+69, Y+23
Button B: X+27, Y+71
Prize: X=18641, Y=10279

Cette liste décrit la configuration des boutons et l'emplacement du prix de quatre machines à griffes différentes.

Pour l'instant, considérez simplement la première machine à griffes de la liste:

    Pousser la machine A Bouton déplacerait la griffe 94 les unités le long de la X axe et 34 les unités le long de la Y axe.
    Pousser le B Bouton déplacerait la griffe 22 les unités le long de la X axe et 67 les unités le long de la Y axe.
    Le prix est situé à l'adresse X=8400, Y=5400; cela signifie qu'à partir de la position initiale de la griffe, il faudrait qu'il se déplace exactement 8400 les unités le long de la X axe et exactement 5400 les unités le long de la Y axe à être parfaitement aligné avec le prix dans cette machine.

Le moyen le moins cher de gagner le prix est de pousser le A bouton 80 et les temps et les B bouton 40 fois. Cela alignerait la griffe le long de la X axe (carré 80*94 + 40*22 = 8400) et le long de la Y axe (carré 80*34 + 40*67 = 5400). Faire cela coûterait cher 80*3 des jetons pour le APresses et 40*1 pour la B presses, un total de 280 jetons.

Pour les deuxième et quatrième machines à griffes, il n'y a pas de combinaison de presses A et B qui remportera un prix.

Pour la troisième machine à griffes, le moyen le moins cher de gagner le prix est de pousser le A bouton 38 et les temps et les B bouton 86 fois. Cela coûterait un total de 200 jetons.

Donc, le plus grand nombre de prix que vous pourriez gagner est deux; les jetons minimum que vous auriez à dépenser pour gagner tous les (deux) prix est 480.

Vous estimez que chaque bouton ne devrait pas être pressé plus que fois de gagner un prix. Comment on s'attendait à ce que quelqu'un joue ?

Découvrez comment gagner autant de prix que possible. Quels sont les quelques-uns que vous auriez à dépenser pour gagner tous les prix possibles?

Votre réponse de puzzle a été *34393*.

--- Deuxième partie ---

Au fur et à mesure que vous gagnez le premier prix, vous découvrez que la griffe est nulle part proche de l'endroit où vous vous attendiez. En raison d'une erreur de conversion unitaire dans vos mesures, la position de chaque prix est en fait 10000000000000 plus élevé sur les deux X et Y axe

Ajouter 10000000000000 à la X et Y position de chaque prix. Après avoir apporté ce changement, l'exemple ci-dessus ressemblerait maintenant à ceci :

Button A: X+94, Y+34
Button B: X+22, Y+67
Prize: X=10000000008400, Y=10000000005400

Button A: X+26, Y+66
Button B: X+67, Y+21
Prize: X=10000000012748, Y=10000000012176

Button A: X+17, Y+86
Button B: X+84, Y+37
Prize: X=10000000007870, Y=10000000006450

Button A: X+69, Y+23
Button B: X+27, Y+71
Prize: X=10000000018641, Y=10000000010279

Or, il n'est possible de gagner qu'un prix sur les deuxième et quatrième machines à griffes. Malheureusement, il faudra beaucoup plus que 100pression pour le faire.

En utilisant les coordonnées du prix corrigée, trouver comment gagner autant de prix que possible. Quels sont les quelques-uns que vous auriez à dépenser pour gagner tous les prix possibles?

Votre réponse de puzzle a été *83551068361379*.

Les deux parties de ce puzzle sont terminées. Ils fournissent deux étoiles d'or:

À ce stade, vous devriez revenir à votre calendrier de l'Avent et essayer un autre puzzle.

Si vous voulez toujours le voir, vous pouvez obtenir votre entrée de puzzle.

Vous pouvez aussi 
