
* --- Jour 4: Ceres Search ---

"On dirait que le chef n'est pas là. Prochainement. » L'un des Historiens tire un appareil et pousse le seul bouton. Après un bref flash, vous reconnaissez l'intérieur de la station de surveillance de Ceres.

Alors que la recherche du chef continue, un petit Elfe qui vit sur la gare remorque votre chemise; elle aimerait savoir si vous pourriez l'aider avec elle recherche de mots (votre saisie d'énigmes). Elle n'a qu'à trouver un mot : XMAS.

Cette recherche de mots permet aux mots d'être horizontal, vertical, diagonal, écrit en arrière, ou même d'autres mots qui se chevauchent. C'est un peu inhabituel, cependant, car vous n'avez pas seulement besoin de trouver un exemple de XMAS - vous devez trouver tous. Voici quelques façons XMAS peuvent apparaître, lorsque des caractères non pertinents ont été remplacés par .:

..X...
.SAMX.
.A..A.
XMAS.S
.X....

La recherche de mots sera plutôt remplie de lettres. Par exemple:

MMMSXXMASM
MSAMXMSMSA
AMXSXMAAMM
MSAMASMSMX
XMASAMXAMM
XXAMMXXAMA
SMSMSASXSS
SAXAMASAAA
MAMMMXMMMM
MXMXAXMASX

Dans cette recherche de mots, XMAS se produit un total de 18 fois; voici la même recherche de mots à nouveau, mais où les lettres n'impliquent aucune XMAS ont été remplacées par .:

....XXMAS.
.SAMXMS...
...S..A...
..A.A.MS.X
XMASAMX.MM
X.....XA.A
S.S.S.S.SS
.A.A.A.A.A
..M.M.M.MM
.X.X.XMASX

Regardez la recherche de mots du petit Elf. Combien de fois fait-il XMASapparait-il?

Votre réponse de puzzle a été *2530*.
--- Deuxième partie ---

L'Elfe vous regarde par bizarrement. As-tu mal compris la mission ?

À la recherche des instructions, vous retournez la recherche de mot pour trouver que ce n'est pas vraiment un XMAS puzzle, c'est un X-MAS puzzle dans lequel vous êtes censé trouver deux MAS en forme de X. Une façon d'y parvenir est la suivante :

M.S
.A.
M.S

Les caractères non pertinents ont de nouveau été remplacés par . dans le schéma ci-dessus. Dans le cadre de la X, chacun MAS peuvent être écrites en avant ou en arrière.

Voici le même exemple d'avant, mais ce temps-là tout le X-MASLes pays ont été conservés à la place:

.M.S......
..A..MSMS.
.M.S.MAA..
..A.ASMSM.
.M.S.M....
..........
S.S.S.S.S.
.A.A.A.A..
M.M.M.M.M.
..........

Dans cet exemple, un X-MAS apparaît 9 fois.

Retournez le mot à partir des instructions à la partie suivante de la recherche de mots et essayez à nouveau. Combien de fois fait-il un X-MASapparait-il?

Votre réponse de puzzle a été *1921*.

Les deux parties de ce puzzle sont terminées. Ils fournissent deux étoiles d'or:

À ce stade, vous devriez revenir à votre calendrier de l'Avent et essayer un autre puzzle.

Si vous voulez toujours le voir, vous pouvez obtenir votre entrée de puzzle.

Vous pouvez aussi [Partager sur Bluesky Twitter Mastodon, cette énigme.
